name: Schema check

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Desired service to replace'
        required: false

      schema_url:
        description: 'Schema URL to replace inside database related to service_name'
        required: false

jobs:
  generate_types_and_ts_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Display SHA code
        run: tmp/scriptssss.sh ${GITHUB_SHA::8}

      - name: Notify if success
        if: ${{ success() }}
        run: |
          echo "Success"

      - name: Notify if failure
        if: ${{ failure() }}
        run: |
          echo "Failure"
